# Generated by Django 3.2.5 on 2021-08-09 11:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_auto_20210809_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='old_passwords',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='processes.usersoldpasswords'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 9, 17, 54, 29, 36211)),
        ),
    ]
