# Generated by Django 3.2.5 on 2021-08-09 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_auto_20210809_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 9, 18, 8, 14, 556962)),
        ),
    ]
