# Generated by Django 3.2.5 on 2021-08-10 09:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('processes', '0006_auto_20210809_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientform',
            name='authorizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='authorizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='citizenship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directories.country'),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='client_checks',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='processes.clientchecks'),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='first_name_english',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='kato',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='processes.katoclient'),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='operationist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operationist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='sex',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='surname_english',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='task_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='tax_registr_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='visa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='processes.visadata'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 10, 15, 8, 14, 599284)),
        ),
    ]
