# Generated by Django 3.2.5 on 2021-08-10 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_auto_20210810_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 10, 15, 8, 48, 200840)),
        ),
    ]
