# Generated by Django 3.2.5 on 2021-08-11 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0010_alter_otp_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_otp',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 11, 11, 53, 40, 353198)),
        ),
    ]
