# Generated by Django 3.2.5 on 2021-08-12 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0011_auto_20210811_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientform',
            name='cif',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 12, 13, 38, 5, 6360)),
        ),
    ]
