# Generated by Django 3.2.5 on 2021-08-17 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0012_auto_20210812_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='old_passwords',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='processes.usersoldpasswords'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 17, 17, 14, 36, 290655)),
        ),
    ]
