# Generated by Django 3.2.5 on 2021-08-20 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('processes', '0013_auto_20210817_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentidentitydata',
            name='country_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directories.country'),
        ),
        migrations.AlterField(
            model_name='documentidentitydata',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentidentitydata',
            name='issue_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentidentitydata',
            name='issued_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 20, 12, 59, 0, 965770)),
        ),
    ]
