# Generated by Django 3.2.5 on 2021-08-20 07:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0014_auto_20210820_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientform',
            name='client_checks',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.clientchecks'),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='document_identity_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='processes.documentidentitydata'),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='kato',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.katoclient'),
        ),
        migrations.AlterField(
            model_name='clientform',
            name='visa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.visadata'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 20, 13, 39, 25, 453842)),
        ),
    ]
