# Generated by Django 3.2.5 on 2021-08-24 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0015_auto_20210820_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='code_word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 24, 19, 42, 30, 198675)),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='is_employee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='length_of_employment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='salary_max',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='salary_min',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
