# Generated by Django 3.2.5 on 2021-08-24 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0016_auto_20210824_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientform',
            name='contact_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.contactdata'),
        ),
        migrations.AddField(
            model_name='clientform',
            name='fatca',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.fatcadata'),
        ),
        migrations.AddField(
            model_name='clientform',
            name='work_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.workinfo'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 24, 22, 31, 21, 371895)),
        ),
    ]
