# Generated by Django 3.2.5 on 2021-08-24 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('processes', '0017_auto_20210824_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katoclient',
            name='district_current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='district_current', to='directories.katodistrict'),
        ),
        migrations.AlterField(
            model_name='katoclient',
            name='district_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='district_registration', to='directories.katodistrict'),
        ),
        migrations.AlterField(
            model_name='katoclient',
            name='region_current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_current', to='directories.katoregion'),
        ),
        migrations.AlterField(
            model_name='katoclient',
            name='region_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_registration', to='directories.katoregion'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 24, 22, 35, 58, 347535)),
        ),
    ]
