# Generated by Django 3.2.5 on 2021-08-24 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0018_auto_20210824_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 24, 23, 10, 46, 58541)),
        ),
    ]
